name: Run pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pipenv

      - name: Setup Pipenv
        uses: tiagovrtr/actions-pipenv@v1
        with:
          pipenv-version: "v2024.1.0"

      - name: Configure caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: precommit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install dependencies
        run: |
          pipenv sync

      - name: Run pre-commit
        run: |
          pipenv run pre-commit run --all-files

      - name: Test if pipeline is up-to-date
        run: |
          pipenv run make pipeline
          git diff --exit-code || (echo "Pipeline is not up-to-date. Please run 'make pipeline' and commit the changes." && exit 1)
